#!/bin/bash

# Convert a jpg or gif image into a base64 representation, that can be
# pasted directly into an html file; there is no need for a separate fetch
# to get the image from the internet.  I have a web page with 400 images;
# it would be very slow to load if it entailed 400 http fetches,
# and the web server might thing it is a DOS attack and lock me out.
# Also useful when sending a self-contained multimedia email.
# Note that the <img tag is left open, so you can add
# alt= width= height= etc.

if [ $# != 1 ]; then
echo "Usage: img264 image-file"
exit 1
fi

# input file output file
inf=$1
if [ ! -f "$inf" ]; then
echo "img264: cannot open $inf"
exit 1
fi
outf=${inf/jpg/64}
outf=${outf/gif/64}
suf=${inf/*./}
if [ ! -f $outf ] ; then
# + in a url attribute means space, so sed translates + to %2B,
# whence the browser turns it back into + which is proper base64.
base64 $inf | sed 's/+/%2B/g' | tr -d '\n' |
sed -e "s/^/<!-- $inf -->\n<img src='data:image\/$suf;base64,/" -e "s/$/'\n/" > $outf
fi
unset inf
unset outf
unset suf
